Feature/text model
philipGaudreau/emotion pull request #26
Opened 2022-07-12 01:54 UTC by gtrottier

2022-07-12 03:53 UTC, philipGaudreau commented on notebooks/cleaning.py
> +cleaning.py
C'est quoi ce fichier?

2022-07-12 03:55 UTC, philipGaudreau requested changes
Enlever le dossier artifacts;
Enlever les fichiers `.py` de _notebooks_;

2022-07-12 03:55 UTC, philipGaudreau commented on notebooks/polarity_balanced.csv
> +id,clean_text,sentiment
Ce fichier est utilisé ou?

2022-07-12 14:15 UTC, philipGaudreau commented on pyproject.toml
> +version = "0.10.12"
Pourquoi on passe de 0.10.9 a 0.10.12?

2022-07-12 14:17 UTC, gtrottier commented on pyproject.toml
> +version = "0.10.12"
aucun raison j'ai fais plusieurs bumps j'pensais push chaque fois

2022-07-12 14:21 UTC, philipGaudreau commented on pyproject.toml
> +version = "0.10.12"
Il faut update de 1 pour la branche principale, pas a chaque push haha!

2022-07-14 17:57 UTC, philipGaudreau approved these changes

2022-07-14 17:57 UTC, merged